// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	request "github.com/ijufumi/email-service/internal/app/http/request"
	mock "github.com/stretchr/testify/mock"
)

// AmazonSESService is an autogenerated mock type for the AmazonSESService type
type AmazonSESService struct {
	mock.Mock
}

// Send provides a mock function with given fields: contents
func (_m *AmazonSESService) Send(contents request.SendMail) error {
	ret := _m.Called(contents)

	var r0 error
	if rf, ok := ret.Get(0).(func(request.SendMail) error); ok {
		r0 = rf(contents)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewAmazonSESService interface {
	mock.TestingT
	Cleanup(func())
}

// NewAmazonSESService creates a new instance of AmazonSESService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAmazonSESService(t mockConstructorTestingTNewAmazonSESService) *AmazonSESService {
	mock := &AmazonSESService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
