// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	request "github.com/ijufumi/email-service/internal/app/http/request"
	mock "github.com/stretchr/testify/mock"
)

// SendGridService is an autogenerated mock type for the SendGridService type
type SendGridService struct {
	mock.Mock
}

// Send provides a mock function with given fields: contents
func (_m *SendGridService) Send(contents request.SendMail) error {
	ret := _m.Called(contents)

	var r0 error
	if rf, ok := ret.Get(0).(func(request.SendMail) error); ok {
		r0 = rf(contents)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewSendGridService interface {
	mock.TestingT
	Cleanup(func())
}

// NewSendGridService creates a new instance of SendGridService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSendGridService(t mockConstructorTestingTNewSendGridService) *SendGridService {
	mock := &SendGridService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
