openapi: 3.0.0
info:
  title: Email Service
  version: '1.0'
  license:
    name: MIT
servers:
  - url: 'http://localhost:8080/api/v1'
paths:
  /health:
    get:
      summary: Check health
      tags: ["Health"]
      responses:
        '200':
          description: OK
      description: Check health of system
  /mail/send:
    post:
      summary: Send a new email
      tags: ["Mail"]
      responses:
        '200':
          description: Email sent successfully
        '400':
          description: Missing required value or invalid format
        '500':
          description: Didn't send a email by several errors
components:
  schemas:
    SendMail:
      title: SendMail
      type: object
      description: Required value to send mail
      x-examples:
        Test mail:
          to_Address: user@ijufumi.jp
          from_address: root@ijufumi.jp
          subject: Notification
          body: This is test mail of notification
      properties:
        to_address:
          type: string
          format: email
        from_address:
          type: string
          format: email
        subject:
          type: string
        body:
          type: string
      required:
        - to_address
        - from_address
        - subject
        - body
