name: test

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
          check-latest: true

      - name: Confirm golang
        run: go version

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...